services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    # Dockerfile path is relative to the repository root
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true # Render can generate this for you
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: laravel-app
          property: url
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password
databases:
  - name: laravel-db
    plan: free
    databaseName: laravel
    user: laravel_user
